Apply example_ynh
YunoHost-Apps/h5ai_ynh pull request #13
Opened 2022-03-31 17:41 UTC by Tagadda

## Problem

- I started using this app :eyes: 

## Solution

- Apply last example_ynh

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-03-31 17:41 UTC, Tagadda commented
!testme

2022-04-01 12:19 UTC, Tagadda commented
!testme

2022-04-03 10:54 UTC, Tagadda commented
!testme

2022-04-04 18:11 UTC, Tagadda commented
The config panel will come in a future PR.

2022-04-04 18:19 UTC, Tagadda commented on scripts/change_url
> +ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1
```suggestion
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=3
```

2022-04-04 18:19 UTC, Tagadda commented on scripts/install
> +ynh_script_progression --message="Setting up source files..." --weight=1
```suggestion
ynh_script_progression --message="Setting up source files..." --weight=4
```

2022-04-04 18:19 UTC, Tagadda commented on scripts/remove
> +ynh_script_progression --message="Removing app main directory..." --weight=1
```suggestion
ynh_script_progression --message="Removing app main directory..." --weight=3
```

2022-04-04 18:19 UTC, Tagadda commented on scripts/restore
> +ynh_script_progression --message="Restoring the app main directory..." --weight=1
```suggestion
ynh_script_progression --message="Restoring the app main directory..." --weight=4
```

2022-04-04 18:19 UTC, Tagadda commented on scripts/remove
>  ynh_secure_remove --file="$final_path"
We should do this only if we have the `--purge` !

2022-04-04 18:19 UTC, Tagadda commented on scripts/remove
> +ynh_secure_remove --file="/etc/$app"
This does not exist ?

2022-04-04 18:19 UTC, Tagadda commented on scripts/upgrade
> +	ynh_script_progression --message="Upgrading source files..." --weight=1
```suggestion
	ynh_script_progression --message="Upgrading source files..." --weight=4
```

2022-04-04 18:22 UTC, Tagadda commented on scripts/remove
> +ynh_secure_remove --file="/etc/$app"
```suggestion
# ...
#=================================================

```

2022-04-04 18:25 UTC, Tagadda commented on scripts/remove
>  ynh_secure_remove --file="$final_path"
We should delete `$final_path/_h5ai` and check for `--purge` to delete `$final_path`

2022-04-04 18:34 UTC, ericgaspar requested changes

2022-04-04 18:34 UTC, ericgaspar commented on scripts/install
> +#=================================================
L.116 to L.137 can be removed I believe

2022-04-04 18:34 UTC, ericgaspar commented on scripts/upgrade
> +
L.125 to L.147 can be removed

2022-04-04 18:34 UTC, ericgaspar commented on scripts/change_url
> +#=================================================
L.94 to L.105 can be removed

2022-04-04 18:34 UTC, ericgaspar commented on scripts/install
> +### `ynh_install_app_dependencies` allows you to add any "apt" dependencies to the package.
Same. we can remove the comments

2022-04-04 18:34 UTC, ericgaspar commented on scripts/remove
> +#=================================================
can be removed

2022-04-04 18:53 UTC, Tagadda commented on scripts/remove
> +#=================================================
what about php ? :thinking:

2022-05-03 23:21 UTC, Tagadda commented on scripts/remove
>  ynh_secure_remove --file="$final_path"
```suggestion
# Remove the app directory securely
ynh_secure_remove --file="$final_path/_h5ai"
```

2022-06-27 11:09 UTC, Tagadda commented
Hey @ericgaspar o/ I'm pretty sure this app needs PHP. Why removing it?

2022-06-27 11:25 UTC, ericgaspar commented
You are right, we need to keep `ynh_remove_app_dependencies` as `ffmpeg` and `imagemagick` are installed but I guess we don't need `php$phpversion-fpm` to be installed... (The current version in master seems to work fine withouth installing `php-fpm.conf`)

2022-08-20 20:28 UTC, Tagadda commented on scripts/install
> +### `ynh_install_app_dependencies` allows you to add any "apt" dependencies to the package.
```suggestion
```

2022-08-20 20:31 UTC, Tagadda commented
!testme

2022-08-20 20:50 UTC, ericgaspar reviewed
Let's upgrade to PHP7.4

2022-08-20 20:50 UTC, ericgaspar commented on scripts/_common.sh
> +phpversion="7.3"
```suggestion
YNH_PHP_VERSION=7.4
```

2022-08-20 20:50 UTC, ericgaspar commented on scripts/_common.sh
> +pkg_dependencies="php$phpversion-fpm ffmpeg imagemagick"
```suggestion
pkg_dependencies="php$YNH_PHP_VERSION-fpm ffmpeg imagemagick"
```

2022-08-20 20:50 UTC, ericgaspar commented on manifest.json
>          "php7.3-fpm"
```suggestion
        "php7.4-fpm"
```

2022-08-26 06:21 UTC, ericgaspar commented
Do we need to increase `upload_max_file_size` and `post_max_size` ?
```
; php_admin_value[upload_max_filesize] = 50M
; php_admin_value[post_max_size] = 50M
```

2022-08-27 01:11 UTC, Tagadda commented
Now you mention it, I guess it should be a config panel option :thinking:

2022-09-09 17:47 UTC, Tagadda commented
👀

2022-10-16 18:28 UTC, merged